### ISSUE TITLE
Steam Guard issue

### ISSUE THREAD

**Issue by awsom82** [synixebrett/Arma3Server#5]
I have a server, how I can authorize it via Steam Guard?

They're also a bug, script come in loop and steam send dozens of emails with steam code every second.

I'm tried `steamcmd`, confirming server, but without luck

**Comment by Knappster** [comment]
From the readme: "The Steam account does not need to own Arma 3, but must have Steam Guard disabled."

Create a throwaway steam account if you're worried about account security.
